org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.42
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5

mod_id=lxdf
mod_name=LX's Drinks And Food
mod_license=All Rights Reserved
mod_version=1.0.0-alpha
mod_group_id=com.liuxss.lxdf
mod_authors=Liuxss
mod_description=LX's Drinks And Food amplía la experiencia culinaria de Minecraft con una variedad de bebidas y alimentos inmersivos, efectos únicos y una integración perfecta con el estilo Vanilla.
